const text = "Should I kill myself or have a cup of coffee?";
const secondText = "Today I prefer coffee.";
const textToTrim = "          coffee        ";
const textLen = text.length;
console.log(textLen);
const textSlice = text.slice(9, 13);
console.log(textSlice);
const textSubstr = text.substr(14, 6);
console.log(textSubstr);
const textReplace = text.replace("coffee", "orange juice");
console.log(textReplace);
const textLower = text.toLowerCase();
console.log(textLower);
const textUpper = text.toUpperCase();
console.log(textUpper);
const textMerge = text.concat(" ", secondText);
console.log(textMerge);
const trimedText = textToTrim.trim();
console.log(trimedText);
const trimedTextOnEnd = textToTrim.trimEnd();
console.log(trimedTextOnEnd);
const trimedTextOnStart = textToTrim.trimStart();
console.log(trimedTextOnStart);
const textPadStart = text.padStart(50, "!");
console.log(textPadStart);
const textPadEnd = text.padEnd(50, "?");
console.log(textPadEnd);
const textChar = text.charAt(7);
console.log(textChar);
const textCharCode = text.charCodeAt(7);
console.log(textCharCode);
const splitedText = text.split(" ");
console.log(splitedText);
